# Generated by Django 5.0.2 on 2024-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(max_length=100000000000000000000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100000000000000000000)),
                ('date', models.CharField(max_length=100000000000000000000)),
                ('authors', models.CharField(max_length=100000000000000000000)),
                ('categories', models.CharField(max_length=100000000000000000000)),
                ('link', models.CharField(max_length=100000000000000000000)),
                ('text', models.CharField(max_length=100000000000000000000)),
                ('citation_rank', models.CharField(max_length=100000000000000000000)),
                ('rank', models.CharField(max_length=100000000000000000000)),
                ('likes', models.CharField(max_length=100000000000000000000)),
            ],
        ),
    ]
