# Generated by Django 5.0.2 on 2024-02-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': False},
        ),
    ]
