# Generated by Django 5.0.2 on 2024-03-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(max_length=1000000, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000000)),
                ('date', models.CharField(max_length=1000000)),
                ('authors', models.CharField(max_length=1000000)),
                ('categories', models.CharField(max_length=1000000)),
                ('link', models.CharField(max_length=1000000)),
                ('text', models.CharField(max_length=1000000)),
                ('citation_rank', models.CharField(max_length=1000000)),
                ('final_rank', models.CharField(max_length=1000000)),
                ('likes', models.CharField(max_length=1000000)),
            ],
            options={
                'db_table': 'app_news',
                'managed': False,
            },
        ),
    ]
